databases:
  - name: budget_expense_app
    databaseName: budget_expense_app
    user: budget_expense_app

services:
  - type: web
    name: budget_expense_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_expense_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false